.azure/scripts/build.sh

This PR fixes default `DOCKER_ORG` in `build.sh`, which should point to the `strimzi-test-clients`.

Fix `DOCKER_ORG` in `build.sh`

---

kafka/admin/src/main/java/AdminConfiguration.java
kafka/consumer/pom.xml
kafka/consumer/src/main/java/ConsumerConfiguration.java
kafka/producer/pom.xml
kafka/producer/src/main/java/ProducerConfiguration.java
kafka/streams/pom.xml
kafka/streams/src/main/java/StreamsConfiguration.java

This PR adds k8s config provider to all other Kafka clients - to producer, consumer and streams.

Add k8s config provider to all other Kafka clients

---

.azure/scripts/build.sh

In #9 building of all images was correct, but we built it with wrong tag -> the images were built with `$COMMIT` tag, but when we wanted to re-tag it (for example to `latest`), the check failed because image with new `DOCKER_TAG` didn't exist. This PR fixes this issue.

Fix docker tag when building images

---

Makefile
Makefile.os
examples/http/http-consumer.yaml
examples/http/http-producer.yaml
examples/kafka/admin-client/alter-topics.yaml
examples/kafka/admin-client/create-topics.yaml
examples/kafka/admin-client/delete-topics.yaml
examples/kafka/admin-client/delete-with-offset-scram512.yaml
examples/kafka/admin-client/delete-with-offset.yaml
examples/kafka/admin-client/list-topics.yaml
examples/kafka/kafka-consumer.yaml
examples/kafka/kafka-producer.yaml
examples/kafka/kafka-streams.yaml

This PR adds more goals to `Makefile` for release process:
- `release_examples` - changes images in all `yaml`s inside the `examples` folder
- `release_version` - changes project `version` to `RELEASE_VERSION` in `pom`s of all modules
- `next_version` -  changes project `version` to `NEXT_VERSION` in `pom`s of all modules
Also changes `image`s inside all example `yaml`s to correct one after #9

Prepare `test-clients` repository for the first release

---

http/http-consumer/pom.xml
http/http-producer/pom.xml
http/pom.xml
kafka/admin/pom.xml
kafka/consumer/pom.xml
kafka/pom.xml
kafka/producer/pom.xml
kafka/streams/pom.xml
pom.xml

The `0.1.0` version is released, so the main branch should be updated:
- changing the versions in all poms of all modules

Bump main to `0.2.0-SNAPSHOT`

---

.azure/build-pipeline.yaml
.azure/scripts/build.sh
.azure/templates/setup_docker.yaml
Makefile.docker
docker-images/build-images.sh
pom.xml

This PR is to add s390x (multi-arch) support to Azure CI to build and push docker images.
The multi-arch test-clients images are built via QEMU and the generated s390x images have been verified on s390x VM.
Signed-off-by: Kun-Lu <kun.lu@ibm.com>

Add s390x support to Azure CI and images

---

.azure/build-pipeline.yaml

This PR adds support for `ppc64le`and `arm64` to our images.

Add `ppc64le` and `arm64` support

---

pom.xml
tracing/pom.xml

In #16 we forgot to add `tracing` module into the main pom file, this PR fixes this issue.

Add tracing module to main pom file

---

tracing/pom.xml

I wrongly added `<packaging>pom</packaging>` into the `tracing` module, which causes to not deliver the `jar`, which is needed as dependency for other modules. This PR fixes this accident.

Remove packaging -> pom from tracing

---

http/http-consumer/pom.xml
http/http-producer/pom.xml
http/pom.xml
kafka/admin/pom.xml
kafka/consumer/pom.xml
kafka/pom.xml
kafka/producer/pom.xml
kafka/streams/pom.xml
pom.xml
tracing/pom.xml

Since `0.2.0` is released, we should update the main branch to point to `0.3.0-SNAPSHOT`

Change version to `0.3.0-SNAPSHOT`

---

.azure/build-pipeline.yaml

Container push is failing due to cyclical reference for DOCKER_USER and DOCKER_PASS:
```
##[warning]Unable to expand variable 'DOCKER_USER'. A cyclical reference was detected.
##[warning]Unable to expand variable 'DOCKER_PASS'. A cyclical reference was detected.
Starting: Push containers
Error: Cannot perform an interactive login from a non TTY device
```
This PR solves that.
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

Remove cyclical reference for docker_user and docker_pass

---

.azure/build-pipeline.yaml
docker-images/build-images.sh

This PR adds proper value for `DOCKER_ORG` which fixes the image builds. It also skips the build of java artifacts during tag. push, etc. At least it passes username and password for docker properly.
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

Use proper org for pushing images, build only for docker_build

---

http/http-consumer/pom.xml
http/http-producer/pom.xml
http/pom.xml
kafka/admin/pom.xml
kafka/consumer/pom.xml
kafka/pom.xml
kafka/producer/pom.xml
kafka/streams/pom.xml
pom.xml
tracing/pom.xml

Because version `0.3.0` of test-clients was released, we should bump the main branch to `0.4.0-SNAPSHOT`

Bump main branch to 0.4.0-SNAPSHOT

---

.azure/build-pipeline.yaml

It seems that when we are building images on tags, the images are just builded and not pushed into the registries.
That means when we are releasing new version of test-clients, the images are not existing after the official release.
This PR fixes this issue.

Fix building images and pushing them for the tags

---

kafka/streams/src/main/java/Main.java
tracing/src/main/java/io/strimzi/test/tracing/OpenTelemetryHandle.java
tracing/src/main/java/io/strimzi/test/tracing/OpenTracingHandle.java
tracing/src/main/java/io/strimzi/test/tracing/TracingHandle.java
tracing/src/main/java/io/strimzi/test/tracing/TracingKafkaClientSupplier.java
tracing/src/main/java/io/strimzi/test/tracing/TracingUtil.java

This PR fixes issue with deploying Kafka Streams client - it seems that with previous implementation, the `Consumer` inside `Kafka Streams` was not able to be deployed, because of the wrong names of the interceptor classes (they have been overwritten).
Instead of using the interceptor classes in properties directly, this PR adds new `TracingKafkaClientSupplier`, which extends the `DefaultKafkaClientSupplier` for creating `KafkaStreams` application with tracing configuration.

Use client supplier wrapper for Kafka Streams client

---

tracing/README.md
tracing/pom.xml
tracing/src/main/java/io/strimzi/test/tracing/OpenTelemetryHandle.java
tracing/src/main/java/io/strimzi/test/tracing/OpenTracingHandle.java
tracing/src/main/java/io/strimzi/test/tracing/TracingConstants.java

This PR changing few things:
1. Deprecates `OpenTracing` handler, which should be then removed in future version of `test-clients`
2. Changes the default OTel exporter to `OTLP`
3. Adding a bit of documentation, what should be set for running tracing clients (like usage of `TRACING_TYPE`)

Deprecated `OpenTracing` and use OTLP exporter as a default exporter for OTel

---

.gitignore
tracing/src/main/java/io/strimzi/test/tracing/HttpHandle.java

It seems that with new bridge version on `main` branch (maybe related to a Vert.x bump), the test-clients try to upgrade from protocol HTTP 1.1 to HTTP 2.0 which is not supported by the bridge and it closes the connection (the clients will raise and EOF exception on its side).
This PR specifies the HTTP 1.1 protocol in the HTTP request to fix this.

Specify HTTP 1.1 version

---

.azure/build-pipeline.yaml
.azure/templates/setup_java.yaml
http/http-consumer/Dockerfile
http/http-producer/Dockerfile
kafka/admin/Dockerfile
kafka/consumer/Dockerfile
kafka/producer/Dockerfile
kafka/streams/Dockerfile
pom.xml

This PR removes support for Java 8 and adds support for Java 17,  which is used on language and also runtime level.
Also this PR bumps `log4j2` and K8s config provider deps.

Move to Java 17 and update few dependencies

---

clients/src/main/java/io/strimzi/Main.java
clients/src/main/java/io/strimzi/common/ClientType.java
clients/src/main/java/io/strimzi/common/configuration/Constants.java
clients/src/main/java/io/strimzi/common/configuration/http/HttpConsumerConfiguration.java
clients/src/main/java/io/strimzi/common/records/http/consumer/ConsumerRecord.java
clients/src/main/java/io/strimzi/common/records/http/consumer/ConsumerRecordUtils.java
clients/src/main/java/io/strimzi/http/consumer/HttpConsumerClient.java
clients/src/test/java/io/strimzi/common/configuration/http/HttpConsumerConfigurationTest.java
clients/src/test/java/io/strimzi/common/records/http/consumer/ConsumerRecordUtilsTest.java

This PR continues in refactoring clients inside this repository - now with HTTP Consumer.
Other than refactoring the HTTP consumer, it also adds switch for the clients -> and depending on `ClientType` runs particular client.

Refactor HTTP consumer

---

clients/src/main/java/io/strimzi/common/records/http/producer/OffsetRecordSent.java
clients/src/main/java/io/strimzi/common/records/http/producer/OffsetRecordSentUtils.java
clients/src/main/java/io/strimzi/common/records/http/producer/ProducerRecord.java
clients/src/main/java/io/strimzi/http/producer/HttpProducerClient.java
clients/src/test/java/io/strimzi/common/records/http/producer/OffsetRecordSentUtilsTest.java
clients/src/test/java/io/strimzi/http/producer/HttpProducerClientTest.java

This PR moves `OffsetRecordSent` and `ProducerRecord` to different package and leaves the producer client package just for the client.
Also, this PR moves methods from `HttpProducerClient` class which are related to `OffsetRecordSent` to `OffsetRecordSentUtils`

Change package for `OffsetRecordSent` and `ProducerRecord`

---

pom.xml

This PR bumps few dependencies used in the test-clients -  Oauth, OpenTelemetry, Log4j2 and other.

Bump few dependencies

---

clients/src/main/java/io/strimzi/Main.java
clients/src/main/java/io/strimzi/common/SaslType.java
clients/src/main/java/io/strimzi/common/configuration/ClientsConfigurationUtils.java
clients/src/main/java/io/strimzi/common/configuration/Constants.java
clients/src/main/java/io/strimzi/common/configuration/kafka/KafkaClientsConfiguration.java
clients/src/main/java/io/strimzi/common/configuration/kafka/KafkaConsumerConfiguration.java
clients/src/main/java/io/strimzi/common/configuration/kafka/KafkaProducerConfiguration.java
clients/src/main/java/io/strimzi/common/configuration/kafka/KafkaStreamsConfiguration.java
clients/src/main/java/io/strimzi/common/properties/KafkaProperties.java
clients/src/main/java/io/strimzi/kafka/KafkaConsumerClient.java
clients/src/main/java/io/strimzi/kafka/KafkaProducerClient.java
clients/src/main/java/io/strimzi/kafka/KafkaStreamsClient.java
clients/src/test/java/io/strimzi/common/configuration/ClientsConfigurationUtilsTest.java
clients/src/test/java/io/strimzi/common/configuration/kafka/KafkaClientsConfigurationTest.java
clients/src/test/java/io/strimzi/common/configuration/kafka/KafkaConsumerConfigurationTest.java
clients/src/test/java/io/strimzi/common/configuration/kafka/KafkaProducerConfigurationTest.java
clients/src/test/java/io/strimzi/common/configuration/kafka/KafkaStreamsConfigurationTest.java
clients/src/test/java/io/strimzi/common/properties/KafkaPropertiesTest.java

This PR refactors all Kafka clients into new `clients` module, with changes to the overall logic.
Also, it merges the Kafka clients configuration (properties) into one file.
As part of this PR, unit tests are added.
Closes #47

Refactor Kafka clients

---

.azure/build-pipeline.yaml

In #56 I added a new build system, but I forgot to add the `--directory=docker-images/` into the make command inside the `Push containers` stage.
This PR fixes it.

Fix push containers

---

clients/src/main/java/io/strimzi/kafka/KafkaProducerClient.java

This PR fixes a small bug inside the KafkaProducer, where we are increasing the number of `messageSuccessfullySent` only after the `producer.send(record).get();` - when we set `acks=all`, we are waiting for the acknowledgment coming back, but in some cases, we can have the `messageIndex` on the desired number of messages, but `messageSuccessfullySent` on much lower number, because for other messages we didn't received the ack back.

Fix race condition where the client will wait for acks, but all messages will be sent

---

.azure/build-pipeline.yaml

This PR updates the image used in AZPs to `Ubuntu-22.04`

Update AZP agent's image to Ubuntu 22.04

---

clients/src/main/java/io/strimzi/common/configuration/Constants.java
clients/src/main/java/io/strimzi/common/configuration/kafka/KafkaClientsConfiguration.java
clients/src/main/java/io/strimzi/kafka/KafkaStreamsClient.java
tracing/src/main/java/io/strimzi/test/tracing/OpenTelemetryHandle.java
tracing/src/main/java/io/strimzi/test/tracing/OpenTracingHandle.java
tracing/src/main/java/io/strimzi/test/tracing/TracingHandle.java
tracing/src/main/java/io/strimzi/test/tracing/TracingUtil.java

This PR should fix the issue with using KafkaStreams client without tracing - in such case, the Job of the client was in Error state, because of the NPE.

Fix the case when we are using KafkaStreams client without tracing

---

docker-images/scripts/run.sh

This PR removes the GC log from the test-clients, as it wasn't useful in the past and the log was not that readable.

Remove GC log from the test-clients

---

admin/src/main/java/io/strimzi/arguments/topic/CreateTopicCommand.java
admin/src/main/java/io/strimzi/utils/ConfigurationUtils.java

This PR adds possibility to specify topic's additional config during its creation in `admin-client`.
It adds two new options:
`--topic-config` - accepts configuration as comma-separated list
`--topic-config-file` - file path to configuration file, from which is the config `Map<String, String>` created and passed to the `NewTopic` during creation
Fixes #73

Add possibility to specify topic's configuration in admin client

---

.azure/build-pipeline.yaml
Makefile
Makefile.docker
admin/README.md
docker-images/Dockerfile
docker-images/scripts/admin-client.sh

Currently we are building executable of admin client using GraalVM, which allows to build native applications.
The problem is that this currently works fine for x86, the problem is in case of architectures like ppc64le, s390x and aarch64.
From what I found, GraalVM doesn't contain feature for cross-platform compiling (so from linux/x86 we cannot build executable for linux/aarch64, etc.)
And because we are using this admin-client in the tests that are also executed on aforementioned platforms, we need to unblock it in some way.
This PR removes the build of executable using GraalVM and instead adds bash script into `/usr/bin` of the container image, so the `admin-client` command will still work and no-one needs to specify `java -jar ..` during each command.
I decided to do it this way now, …

Admin-client - use bash script inside the client's container instead of building executable

---

pom.xml

This PR bumps dependencies of `jackson` and `oauth` to newer versions

Bump dependencies - `jackson` and `oauth`

---

admin/src/main/java/io/strimzi/Main.java
admin/src/main/java/io/strimzi/arguments/topic/DescribeTopicCommand.java
admin/src/main/java/io/strimzi/models/KafkaTopicDescription.java
admin/src/main/java/io/strimzi/utils/DescribeTopicsUtils.java
admin/src/main/java/io/strimzi/utils/OutputFormat.java

PR adds implementation for correct handling of `topic describe` command. 
for smoother work with topic description also output format option is added with json and plain possible values. 
Because we are supporting values with options to fool proof the work with them they are set to case insensitive (as error logs provides them in Upper case it is easier to allow that as well).

add -o --output json, plain option for describe topic

---

admin/src/main/java/io/strimzi/arguments/BasicCommand.java
admin/src/main/java/io/strimzi/arguments/configure/ConfigureCommand.java
admin/src/main/java/io/strimzi/arguments/topic/AlterTopicCommand.java
admin/src/main/java/io/strimzi/arguments/topic/BasicTopicCommand.java
admin/src/main/java/io/strimzi/arguments/topic/DeleteTopicCommand.java
admin/src/main/java/io/strimzi/arguments/topic/DescribeTopicCommand.java
admin/src/main/java/io/strimzi/arguments/topic/IfExistsTopicCommand.java
admin/src/main/java/io/strimzi/arguments/topic/TopicCommand.java

This PR adds possibility to specify, if the topics that are not present in Kafka during operations delete, describe, and alter, should or should not be ignored - by specifying the `--if-exists` flag.
Also, this PR fixes the `--help` option not working in most of the sub-commands.
Closes #83

Add --if-exists option to topic delete, describe, and alter subcommands and fix --help option functionality

---

admin/src/main/java/io/strimzi/admin/AdminProperties.java
admin/src/main/java/io/strimzi/utils/ConfigurationUtils.java

This PR fixes following log:
```
Failed to load configuration file - no such file exist
```
which appears every time we execute command and we didn't configure the Admin's properties:
```
> admin-client topic create --bootstrap-server localhost:9092 -t my-topic -tp 1 -trf 1                                                                                                                                                                                     
Failed to load configuration file - no such file exist
Topic(s) with name(prefix): [(name=my-topic, numPartitions=1, replicationFactor=1, replicasAssignments=null, configs={})] and count 1 successfully created
```
This log can confuse others, because it seems like something went wrong, even though the operation was finished successful.

Fix log about non-existing admin-client properties file

---

clients/src/main/java/io/strimzi/kafka/KafkaConsumerClient.java

When there is a commit offset timeout, the whole consumer is stopped. In our tests it is not suitable solution as during upgrades it can happen from time to time. This change just notify about commit timeout and will keep the default functionality of Kafka Consumer that will retry it again. This change also keep in place expected behavior of fail fast in case of oauth exceptions.

Handle commit timeout exception instead of fail whole consumer

---

Makefile.docker

This PR adds `DOCKER_CMD` env variable to the `Makefile.docker`, so we are able to use the make targets also with other engine -> like `podman`.

Add DOCKER_CMD for running the make commands also with other engines like Podman

---

Makefile

This small PR fixes issue with the `make next_version` and `make release_clients_version` commands, which wrongly passed the "version" env variable to the `clients.version` file. On Mac, when someone executed one of these commands, the `-n DESIRED_VERSION` + newline was added into the file (where the `-n` should work as an option to **not add the newline**).
Instead of the option I'm adding the `\c` which works the same way, but on every system.

Correct echo command in the Makefile

---

clients/src/main/java/io/strimzi/http/consumer/HttpConsumerClient.java

In case the consumer pod gets restarted (due to migration to different node for example), the connection fail, because the consumer with that name already exists in Kafka Bridge. This change allow us to continue with the consumer in such situations.

Continue consumer when it already exists in HTTP Bridge

---

.azure/build-pipeline.yaml
clients-common/pom.xml
clients/pom.xml
clients/src/test/java/io/strimzi/common/records/consumer/http/ConsumerRecordUtilsTest.java
clients/src/test/java/io/strimzi/common/records/consumer/kafka/KafkaConsumerRecordTest.java
clients/src/test/java/io/strimzi/common/records/producer/http/OffsetRecordSentUtilsTest.java
clients/src/test/java/io/strimzi/configuration/http/HttpClientsConfigurationTest.java
clients/src/test/java/io/strimzi/configuration/kafka/KafkaConsumerConfigurationTest.java
clients/src/test/java/io/strimzi/configuration/kafka/KafkaProducerConfigurationTest.java
clients/src/test/java/io/strimzi/producer/kafka/KafkaProducerClientTest.java
pom.xml

Until now the unit tests we have in the test-clients repository were not running (at all). There were few issues:
- we had JUnit4 used during the test execution, which caused that no tests were found during `mvn install` or `mvn test`
- the Surefire plugin was missing
- old dependencies/plugins were used (this is connected to the JUnit4 point)
- the step was missing in the build pipeline to actually run the tests (it should have been done during `mvn install`, but it wasn't because of the issues mentioned above)
This PR fixes this issue, together with small clean-up of the dependencies, removal of unused stuff and few bumps of dependencies.

Fix running tests in build pipeline (and overall)

---

README.md
admin/pom.xml
clients-common/pom.xml
clients-common/src/main/java/io/strimzi/configuration/ConfigurationConstants.java
clients/pom.xml
clients/src/main/java/io/strimzi/common/MessageType.java
clients/src/main/java/io/strimzi/configuration/http/HttpClientsConfiguration.java
clients/src/main/java/io/strimzi/configuration/http/HttpProducerConfiguration.java
clients/src/main/java/io/strimzi/configuration/kafka/KafkaProducerConfiguration.java
clients/src/main/java/io/strimzi/http/consumer/HttpConsumerClient.java
clients/src/main/java/io/strimzi/http/producer/HttpProducerClient.java
clients/src/main/java/io/strimzi/kafka/KafkaProducerClient.java
clients/src/test/java/io/strimzi/configuration/kafka/KafkaProducerConfigurationTest.java
clients/src/test/java/io/strimzi/producer/http/HttpProducerClientTest.java
pom.xml
tracing/pom.xml

This PR do the several things:
- Add [data-generator](https://github.com/skodjob/data-generator) dependency to allow generate reasonable messages
- Add option `MESSAGE_TEMPLATE` that refers which template from data-geenrator should be used
- Add option `MESSAGE_TYPE` to indicate how the message should be handled by the clients (text or json atm)
The build will fail until we will release new version of data-generator. I will keep this in draft until we will discuss further steps with the team.
It also resolves https://github.com/strimzi/test-clients/issues/96

Use data-generator for creating messages payload, add option to specify template and message format type

---

clients/src/main/java/io/strimzi/common/records/consumer/http/ConsumerRecord.java
clients/src/test/java/io/strimzi/common/records/consumer/http/ConsumerRecordUtilsTest.java

After https://github.com/strimzi/strimzi-kafka-bridge/pull/915 was added into Bridge, we need to handle it in our `ConsumerRecord` for HTTP response -> because without that, we are getting:
```
2024-08-01 16:24:45.758.12287383472543 [1;31mERROR[m HttpConsumerClient:175 - Failed to consume message due to: Unrecognized field "timestamp" (class io.strimzi.common.records.http.consumer.ConsumerRecord), not marked as ignorable (5 known properties: "value", "partition", "offset", "topic", "key"])
at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 130] (through reference chain: java.lang.Object[][0]->io.strimzi.common.records.http.consumer.ConsumerRecord["timestamp"])
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized …
```

Handle timestamp value in response from Bridge

---

clients/pom.xml
clients/src/main/java/io/strimzi/common/properties/KafkaProperties.java
clients/src/main/java/io/strimzi/configuration/kafka/KafkaConsumerConfiguration.java
clients/src/main/java/io/strimzi/configuration/kafka/KafkaProducerConfiguration.java
clients/src/main/java/io/strimzi/configuration/kafka/KafkaStreamsConfiguration.java
clients/src/main/java/io/strimzi/http/producer/HttpProducerClient.java
clients/src/main/java/io/strimzi/kafka/KafkaProducerClient.java
clients/src/test/java/io/strimzi/common/properties/KafkaPropertiesTest.java
pom.xml

We would like to use schema registry with test-clients. This allow us to use apicurio serdes for using clients together with schema registry implementations.

Make Avro serdes configurable

---

clients/pom.xml
clients/src/test/java/io/strimzi/integration/AbstractIT.java
clients/src/test/java/io/strimzi/integration/KafkaClientIT.java
clients/src/test/java/io/strimzi/integration/KafkaClientWithRegistryIT.java
clients/src/test/java/io/strimzi/unit/common/properties/KafkaPropertiesTest.java
clients/src/test/java/io/strimzi/unit/common/records/consumer/http/ConsumerRecordUtilsTest.java
clients/src/test/java/io/strimzi/unit/common/records/consumer/kafka/KafkaConsumerRecordTest.java
clients/src/test/java/io/strimzi/unit/common/records/producer/http/OffsetRecordSentUtilsTest.java
clients/src/test/java/io/strimzi/unit/configuration/http/HttpClientsConfigurationTest.java
clients/src/test/java/io/strimzi/unit/configuration/http/HttpConsumerConfigurationTest.java
clients/src/test/java/io/strimzi/unit/configuration/http/HttpProducerConfigurationTest.java
clients/src/test/java/io/strimzi/unit/configuration/kafka/KafkaConsumerConfigurationTest.java
clients/src/test/java/io/strimzi/unit/configuration/kafka/KafkaProducerConfigurationTest.java
clients/src/test/java/io/strimzi/unit/configuration/kafka/KafkaStreamsConfigurationTest.java
clients/src/test/java/io/strimzi/unit/producer/http/HttpProducerClientTest.java
clients/src/test/java/io/strimzi/unit/producer/kafka/KafkaProducerClientTest.java
pom.xml

This PR adds integration tests with apicurio registry to verify that messaged generated in Avro format works properly on both clients - producer and consumer.

Add more ITs with apicurio to verify proper work of avro data

---

admin/src/main/java/io/strimzi/admin/KafkaAdminClient.java
admin/src/main/java/io/strimzi/arguments/nodes/DescribeNodeCommand.java
admin/src/main/java/io/strimzi/arguments/nodes/NodeCommand.java
admin/src/main/java/io/strimzi/constants/Constants.java
admin/src/main/java/io/strimzi/utils/DescribeNodesUtils.java
examples/admin/admin-client.yaml

This PR adds support for describing the nodes of the Kafka cluster using our `admin-client`.
The output of the command:
for `plain` output format:
```
> admin-client node describe --bootstrap-server my-cluster-kafka-bootstrap.kafka.svc:9092 --node-ids all --output plain
Node 0
hostname: my-cluster-broker-0.my-cluster-kafka-brokers.kafka.svc:9092
node ID: 0
rack: null
Node 1
hostname: my-cluster-broker-1.my-cluster-kafka-brokers.kafka.svc:9092
node ID: 1
rack: null
Node 2
hostname: my-cluster-broker-2.my-cluster-kafka-brokers.kafka.svc:9092
node ID: 2
rack: null
Node 6
hostname: my-cluster-broker-6.my-cluster-kafka-brokers.kafka.svc:9092
node ID: 6
rack: null
``` 
for `json` output format:
```
> admin-client node describe --bootstrap-server my-cluster-kafka-bootstrap.kafka.svc:9092 …
```

Add support for describing nodes using Admin client

---

docker-images/Dockerfile
docker-images/scripts/admin-client.sh
docker-images/scripts/run.sh

Using `java -jar` prevents updating the classpath and adding custom plugins to the clients. Instead I propose using the `-cp` flag so users can append paths to the classpath.

Allow updating the classpath when starting clients

---

admin/pom.xml
admin/src/test/java/admin/integration/AbstractIT.java
admin/src/test/java/admin/integration/AdminTopicIT.java

This PR adds ITs for `admin-client topic` command - for all of the operations available (`create`, `describe`, `list`, `alter`, `delete`), which were missing for quite a long time.

Add ITs for admin-client topic commands

---

admin/pom.xml
admin/src/test/java/admin/integration/AdminNodeIT.java
admin/src/test/java/admin/integration/AdminTopicIT.java
pom.xml

This PR adds IT for `admin-client node describe` command and one more for the topic command -> for the `fetch-offsets` command.
Additionally, it little bit clears up the deps in pom.xmls.

Add IT for admin-client node command and one test for fetch-offsets
